modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="glowberry_expantion"
version="1.0.0"
displayName="Glowberry Expantion"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Sabien, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.glowberry_expantion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.glowberry_expantion]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.glowberry_expantion]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration